version: '3.8'

services:
  # LeanVibe Backend API
  backend:
    build:
      context: ./leanvibe-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
    volumes:
      - ./leanvibe-backend:/app
      - backend_data:/app/data
    depends_on:
      - ollama
    networks:
      - leanvibe-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    networks:
      - leanvibe-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  backend_data:
    driver: local
  ollama_data:
    driver: local

networks:
  leanvibe-network:
    driver: bridge
EOF < /dev/null