services:
  neo4j:
    image: neo4j:5.17-community
    container_name: leanvibe-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/leanvibe123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - leanvibe-network

  chroma:
    image: chromadb/chroma:latest
    container_name: leanvibe-chroma
    restart: unless-stopped
    ports:
      - "8001:8000"  # Chroma HTTP API (mapped to 8001 to avoid conflict with backend)
    environment:
      CHROMA_SERVER_HOST: 0.0.0.0
      CHROMA_SERVER_HTTP_PORT: 8000
      CHROMA_SERVER_CORS_ALLOW_ORIGINS: '["*"]'
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - leanvibe-network

  # Redis for caching (optional but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: leanvibe-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - leanvibe-network

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  chroma_data:
    driver: local
  redis_data:
    driver: local

networks:
  leanvibe-network:
    driver: bridge