# LeanVibe Documentation Maintenance Configuration
# Enterprise-grade configuration for automated documentation maintenance system

# Global Settings
global:
  version: "1.0.0"
  environment: "production"  # production, staging, development
  timezone: "UTC"
  
# Documentation Sources
sources:
  # Primary documentation directory
  docs_directory: "."
  
  # API source files
  api_sources:
    - "app/api/endpoints/**/*.py"
    - "app/main.py"
    - "app/api/models.py"
  
  # Model source files  
  model_sources:
    - "app/models/**/*.py"
    - "app/api/models.py"
  
  # Configuration files
  config_sources:
    - "app/config/**/*.py"
    - "pyproject.toml"
    - "*.yaml"
    - "*.yml"
  
  # Deployment files
  deployment_sources:
    - "k8s/**/*.yaml"
    - "terraform/**/*.tf"
    - "docker-compose*.yml"
    - "Dockerfile*"
  
  # Contract files
  contract_sources:
    - "contracts/**/*"
    - "*.json"

# Output Configuration
output:
  # Generated documentation directory
  generated_docs_dir: "docs/generated"
  
  # Main documentation files to update
  target_files:
    api_documentation: "API.md"
    openapi_spec: "contracts/openapi.yaml"
    postman_collection: "LeanVibe_API.postman_collection.json"
    enterprise_docs: "API_ENTERPRISE.md"
  
  # Backup settings
  backup:
    enabled: true
    retention_days: 30
    backup_dir: ".claude/docs_backups"

# Quality Standards
quality_standards:
  # Minimum scores (0-100)
  min_overall_score: 80.0
  min_writing_quality: 85.0
  min_technical_accuracy: 90.0
  min_accessibility: 95.0
  min_enterprise_compliance: 90.0
  
  # Content requirements
  max_reading_level: 12.0  # Grade level
  min_word_count: 100
  max_line_length: 120
  
  # Structure requirements
  require_headings: true
  require_introduction: true
  require_examples: true
  require_table_of_contents: true  # For docs > 1500 words
  
  # Enterprise requirements
  require_contact_info: true
  require_version_info: true
  require_legal_compliance: true
  require_security_documentation: true

# Validation Settings
validation:
  # Link validation
  validate_external_links: true
  validate_internal_links: true
  external_link_timeout: 30  # seconds
  trusted_domains:
    - "github.com"
    - "docs.python.org" 
    - "fastapi.tiangolo.com"
    - "kubernetes.io"
    - "docker.com"
    - "leanvibe.ai"
  
  # Code validation
  validate_code_examples: true
  supported_languages:
    - "python"
    - "javascript"
    - "bash"
    - "json"
    - "yaml"
    - "sql"
  
  # Content validation
  check_spelling: true
  check_grammar: true
  check_accessibility: true
  validate_api_endpoints: true

# Change Detection
change_detection:
  # Monitoring intervals
  check_interval_hours: 1
  daily_health_check: true
  weekly_deep_analysis: true
  
  # Sensitivity settings
  monitor_api_changes: true
  monitor_model_changes: true
  monitor_config_changes: true
  monitor_deployment_changes: true
  monitor_file_structure: true
  
  # Change thresholds
  minor_change_threshold: 5  # % of content changed
  major_change_threshold: 20
  critical_change_threshold: 50
  
  # Git integration
  analyze_recent_commits: true
  commit_analysis_days: 7
  create_github_issues: true
  
# Automation Settings
automation:
  # Auto-update triggers
  auto_update_docs: true
  auto_create_prs: true
  auto_notify_maintainers: true
  
  # Update frequency
  immediate_updates:
    - "critical_api_changes"
    - "security_updates"
    - "breaking_changes"
  
  daily_updates:
    - "minor_api_changes"
    - "configuration_updates"
    - "quality_improvements"
  
  weekly_updates:
    - "comprehensive_review"
    - "link_validation"
    - "content_freshness"
  
  # Automation limits
  max_auto_prs_per_day: 3
  min_time_between_updates: 2  # hours
  require_human_approval:
    - "breaking_changes"
    - "enterprise_compliance"
    - "legal_documentation"

# Enterprise Features
enterprise:
  # SLA Requirements
  sla_targets:
    max_broken_links: 0
    max_outdated_docs_days: 30
    min_quality_score: 85.0
    max_response_time_ms: 2000
    min_uptime_percentage: 99.9
  
  # Compliance requirements
  compliance:
    gdpr_compliant: true
    sox_compliant: true
    hipaa_aware: false
    iso27001_aligned: true
  
  # Required documentation sections
  required_sections:
    - "enterprise_features"
    - "security_architecture"
    - "compliance_information"
    - "sla_commitments"
    - "support_escalation"
    - "data_residency"
  
  # Enterprise notifications
  notifications:
    slack_webhook_url: ""  # Set in environment variables
    teams_webhook_url: ""  # Set in environment variables
    email_notifications: true
    pagerduty_integration: false

# Monitoring & Observability
monitoring:
  # Health check intervals
  health_check_interval: "*/15 * * * *"  # Every 15 minutes
  deep_health_check_interval: "0 6 * * *"  # Daily at 6 AM
  
  # Metrics collection
  collect_usage_metrics: true
  collect_performance_metrics: true
  collect_quality_metrics: true
  
  # Alerting thresholds
  alert_thresholds:
    critical_quality_score: 70.0
    warning_quality_score: 80.0
    max_broken_links: 3
    max_response_time_ms: 3000
  
  # Retention settings
  metrics_retention_days: 90
  log_retention_days: 30
  report_retention_days: 365

# Integration Settings
integrations:
  # Version control
  git:
    main_branch: "main"
    development_branch: "develop"
    feature_branch_prefix: "docs/"
    auto_commit: true
    commit_message_template: |
      docs: Automated documentation update
      
      🤖 Generated with LeanVibe Documentation Maintenance System
      
      Changes:
      {changes_summary}
      
      Quality Score: {quality_score}/100
      Co-authored-by: Documentation Bot <action@github.com>
  
  # External services
  external_services:
    analytics_api: ""  # Google Analytics, etc.
    cdn_api: ""        # CloudFlare, AWS CloudFront, etc.
    monitoring_api: "" # DataDog, New Relic, etc.
  
  # CI/CD Integration
  cicd:
    github_actions: true
    gitlab_ci: false
    jenkins: false
    
    # Workflow triggers
    trigger_on_push: true
    trigger_on_pr: true
    trigger_on_schedule: true
    trigger_on_manual: true

# Security Settings
security:
  # Secrets management
  secrets_provider: "github_secrets"  # github_secrets, vault, k8s_secrets
  
  # Access control
  require_approvals: true
  approval_count: 1
  approved_teams:
    - "documentation-team"
    - "engineering-leads"
  
  # Security scanning
  scan_for_secrets: true
  scan_for_vulnerabilities: true
  allowed_domains:
    - "*.leanvibe.ai"
    - "*.github.com"
    - "api.github.com"
  
  # Content security
  sanitize_output: true
  validate_urls: true
  check_content_safety: true

# Performance Settings  
performance:
  # Processing limits
  max_concurrent_validations: 10
  max_file_size_mb: 50
  timeout_seconds: 300
  
  # Caching
  enable_caching: true
  cache_ttl_hours: 24
  cache_directory: ".claude/cache"
  
  # Resource limits
  max_memory_mb: 2048
  max_cpu_percentage: 80

# Localization (Future)
localization:
  default_language: "en"
  supported_languages:
    - "en"
  
  # Translation settings (placeholder)
  auto_translate: false
  translation_provider: ""
  
# Custom Rules
custom_rules:
  # Content rules
  content_patterns:
    prohibited_words: []
    required_phrases: []
    brand_terminology: {}
  
  # File naming conventions
  naming_conventions:
    docs_prefix: ""
    docs_suffix: ""
    case_style: "kebab-case"  # kebab-case, snake_case, camelCase
  
  # Custom validation rules
  validation_rules: []

# Feature Flags
feature_flags:
  experimental_ai_analysis: false
  advanced_metrics: true
  real_time_monitoring: false
  multi_language_support: false
  
# Debug & Development
debug:
  enabled: false
  verbose_logging: false
  save_intermediate_results: false
  skip_external_calls: false
  
# Maintenance Windows
maintenance:
  # Scheduled maintenance (when to avoid updates)
  windows:
    - start: "23:00"
      end: "01:00"
      timezone: "UTC"
      description: "Database maintenance window"
  
  # Emergency procedures
  emergency_mode: false
  emergency_contacts:
    - "docs-team@leanvibe.ai"
    - "engineering@leanvibe.ai"