# LeanVibe Enterprise Configuration Management
# Environment-specific configuration with tenant isolation
apiVersion: v1
kind: ConfigMap
metadata:
  name: leanvibe-config
  namespace: leanvibe-production
  labels:
    app.kubernetes.io/name: leanvibe
    app.kubernetes.io/component: config
    environment: production
data:
  # Application Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
  
  # Multi-Tenancy Configuration
  DEFAULT_TENANT_TIER: "team"
  TENANT_ISOLATION_ENABLED: "true"
  MAX_TENANTS_PER_INSTANCE: "100"
  
  # Performance Configuration  
  WORKERS: "4"
  MAX_CONNECTIONS: "1000"
  CONNECTION_POOL_SIZE: "20"
  CONNECTION_POOL_MAX_OVERFLOW: "10"
  
  # Cache Configuration
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1000"
  
  # Monitoring Configuration
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  PERFORMANCE_MONITORING: "true"
  
  # Security Configuration
  SESSION_TIMEOUT: "1800"
  MAX_LOGIN_ATTEMPTS: "5"
  PASSWORD_MIN_LENGTH: "12"
  
  # Business Logic Configuration
  MAX_PROJECTS_PER_TENANT: "50"
  MAX_FILES_PER_PROJECT: "1000"
  MAX_FILE_SIZE_MB: "10"
  
  # Enterprise Features
  SSO_ENABLED: "true"
  SAML_ENABLED: "true"
  MFA_REQUIRED: "true"
  AUDIT_LOGGING: "true"
  
  # Billing Configuration
  BILLING_ENABLED: "true"
  USAGE_TRACKING: "true"
  INVOICE_GENERATION: "true"
  
  # AI Service Configuration
  AI_MODEL_TIMEOUT: "30"
  AI_MAX_TOKENS: "4000"
  AI_TEMPERATURE: "0.7"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: leanvibe-database-config
  namespace: leanvibe-production
  labels:
    app.kubernetes.io/name: leanvibe
    app.kubernetes.io/component: database
    environment: production
data:
  # Neo4j Configuration
  NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
  NEO4J_apoc_export_file_enabled: "true"
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_MEMORY_HEAP_INITIAL_SIZE: "2G"
  NEO4J_MEMORY_HEAP_MAX_SIZE: "4G"
  NEO4J_dbms_memory_pagecache_size: "2G"
  NEO4J_dbms_logs_query_enabled: "INFO"
  NEO4J_dbms_logs_query_threshold: "1s"
  
  # Connection Settings
  NEO4J_dbms_connector_bolt_thread_pool_min_size: "5"
  NEO4J_dbms_connector_bolt_thread_pool_max_size: "400"
  NEO4J_dbms_connector_bolt_thread_pool_keep_alive: "5m"
---
apiVersion: v1
kind: ConfigMap  
metadata:
  name: leanvibe-redis-config
  namespace: leanvibe-production
  labels:
    app.kubernetes.io/name: leanvibe
    app.kubernetes.io/component: redis
    environment: production
data:
  redis.conf: |
    # Redis Production Configuration for LeanVibe Enterprise
    
    # Memory Management
    maxmemory 2gb
    maxmemory-policy allkeys-lru
    
    # Persistence Configuration
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfsync everysec
    
    # Network Configuration  
    tcp-keepalive 300
    timeout 300
    
    # Security Configuration
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command DEBUG ""
    rename-command CONFIG ""
    
    # Performance Tuning
    tcp-backlog 511
    databases 16
    
    # Multi-tenant key prefix support
    # Keys will be prefixed with tenant IDs for isolation